name = "genetia-watcher-1"
main = "src/index.ts"
compatibility_date = "2026-09-04"
compatibility_flags = ["nodejs_compat"]
[vars]
WATCHER_ID = "watcher-1"
GENLAYER_RPC = "https://studio-dev.genlayer.com/api"
