import { Hono } from "hono";
import { z } from "zod";
import { CHAIN, ProposalSchema } from "@genetia/shared";
type Env = { DB?: Hyperdrive; BASE_CHAIN_ID:string; GENLAYER_CHAIN_ID:string; GENLAYER_RPC:string };
const app = new Hono<{Bindings:Env}>().basePath("/api");
const id = z.string().min(1).max(128);
const address = z.string().regex(/^0x[0-9a-fA-F]{40}$/);
app.get("/health", c=>c.json({ok:true, baseChainId:CHAIN.base, genlayerChainId:CHAIN.genlayer}));
app.get("/markets", c=>c.json({error:"indexed market source is not configured"},503));
app.get("/markets/:id", c=>{id.parse(c.req.param("id"));return c.json({error:"market index unavailable"},404)});
for (const suffix of ["prices","trades","liquidity","resolution","evidence"]) app.get(`/markets/:id/${suffix}`, c=>{id.parse(c.req.param("id"));return c.json({error:"indexed market source is not configured"},503);});
app.post("/markets/:id/quote", c=>{id.parse(c.req.param("id"));return c.json({error:"on-chain quote required"},400)});
app.post("/markets/:id/prepare-trade", c=>{id.parse(c.req.param("id"));return c.json({error:"wallet authorization required"},400)});
app.post("/market-proposals", async c=>{
  const parsed = ProposalSchema.safeParse(await c.req.json().catch(()=>undefined));
  if (!parsed.success) return c.json({error:"invalid proposal", issues: parsed.error.issues},400);
  return c.json({error:"proposal workflow is not configured"},503);
});
app.get("/market-proposals/:id", c=>{id.parse(c.req.param("id"));return c.json({error:"proposal source is not configured"},503)});
app.get("/users/:address/positions", c=>{address.parse(c.req.param("address"));return c.json({error:"indexed position source is not configured"},503)});
app.get("/users/:address/history", c=>{address.parse(c.req.param("address"));return c.json({error:"indexed history source is not configured"},503)});
export default app;
