export type MarketPolicyInput = {
  id: string;
  category?: string | null;
  status?: string | null;
  lmsrStatus?: string | null;
  expiry?: Date | string | null;
  resolutionSource?: string | null;
  createdBy?: string | null;
};

export type UserPolicyInput = {
  id?: string | null;
  email?: string | null;
  isAdmin?: boolean | null;
};

export type MarketPolicy = {
  marketCategory: string;
  regionTag: string;
  restricted: boolean;
  requiresIdentity: boolean;
  minTradeAmount: number;
  maxTradeAmount: number;
  settlementAsset: string;
  marketCreator: string;
  evidenceStandard: string;
  enforcement: "app-level" | "contract-enforced" | "simulated";
};

export type PolicyDecision = {
  allowed: boolean;
  reasons: string[];
  policy: MarketPolicy;
};

const DEFAULT_MIN_TRADE_USDC = Number(process.env.NEXT_PUBLIC_MIN_TRADE_USDC ?? "0.01");
const DEFAULT_MAX_TRADE_USDC = Number(process.env.NEXT_PUBLIC_MAX_TRADE_USDC ?? "5000");

export function getMarketPolicy(market: MarketPolicyInput): MarketPolicy {
  const category = (market.category ?? "general").trim().toLowerCase() || "general";

  return {
    marketCategory: category,
    regionTag: "global-testnet",
    restricted: false,
    requiresIdentity: true,
    minTradeAmount: DEFAULT_MIN_TRADE_USDC,
    maxTradeAmount: DEFAULT_MAX_TRADE_USDC,
    settlementAsset: "USDC on Arc Testnet",
    marketCreator: market.createdBy ?? "admin-curated",
    evidenceStandard: market.resolutionSource
      ? "At least one configured URL source; GenLayer must use supplied evidence only."
      : "Evidence URL required before resolver submission.",
    enforcement: "app-level",
  };
}

export function canViewMarket(
  _user: UserPolicyInput | null | undefined,
  market: MarketPolicyInput
): PolicyDecision {
  const policy = getMarketPolicy(market);
  const reasons: string[] = [];

  if (market.status === "archived") {
    reasons.push("Archived markets are hidden from the public market list.");
  }

  return { allowed: reasons.length === 0, reasons, policy };
}

export function canTradeMarket(
  user: UserPolicyInput | null | undefined,
  market: MarketPolicyInput,
  opts: { amount?: number } = {}
): PolicyDecision {
  const policy = getMarketPolicy(market);
  const reasons: string[] = [];
  const expiry = market.expiry ? new Date(market.expiry) : null;

  if (policy.requiresIdentity && !user?.id) {
    reasons.push("Trading requires an authenticated app user.");
  }
  if (market.status !== "active") {
    reasons.push(`Market status is ${market.status ?? "unknown"}, not active.`);
  }
  if (market.lmsrStatus && market.lmsrStatus !== "Active") {
    reasons.push(`Arc market status is ${market.lmsrStatus}, not Active.`);
  }
  if (expiry && expiry.getTime() <= Date.now()) {
    reasons.push("Trading is closed because the market has expired.");
  }
  if (opts.amount !== undefined && Number.isFinite(opts.amount)) {
    if (opts.amount < policy.minTradeAmount) {
      reasons.push(`Minimum trade size is ${policy.minTradeAmount} USDC.`);
    }
    if (opts.amount > policy.maxTradeAmount) {
      reasons.push(`Maximum trade size is ${policy.maxTradeAmount} USDC in this MVP.`);
    }
  }

  return { allowed: reasons.length === 0, reasons, policy };
}

export function canCreateMarket(user: UserPolicyInput | null | undefined): PolicyDecision {
  const policy = getMarketPolicy({ id: "new-market", category: "general" });
  const reasons: string[] = [];
  if (!user?.isAdmin) {
    reasons.push("Market creation is admin-curated in this MVP.");
  }
  return { allowed: reasons.length === 0, reasons, policy };
}

export function getMarketRestrictions(market: MarketPolicyInput): string[] {
  const policy = getMarketPolicy(market);
  const restrictions = [
    `Settlement asset: ${policy.settlementAsset}`,
    `Policy scope: ${policy.regionTag}`,
    `Identity checks: ${policy.requiresIdentity ? "app-level Privy account required" : "not required"}`,
    `Trade limits: ${policy.minTradeAmount}-${policy.maxTradeAmount} USDC`,
    `Evidence standard: ${policy.evidenceStandard}`,
  ];

  if (policy.restricted) {
    restrictions.push("This market is restricted by app-level policy.");
  }

  return restrictions;
}

export function getComplianceDisclosure(market: MarketPolicyInput): string[] {
  const policy = getMarketPolicy(market);
  return [
    "Trading and redemption are enforced by Arc LMSR contracts.",
    "Resolution is generated by GenLayer and submitted by a trusted relayer/app pipeline.",
    "Identity and market policy checks are app-level MVP controls, not a full legal compliance system.",
    "Admin controls exist for testnet safety and challenged-market adjudication.",
    `Current policy enforcement: ${policy.enforcement}.`,
  ];
}
